### ISSUE TITLE
Multilingual table/fields

### ISSUE THREAD

**Issue by panakour** [daptin/daptin#68] opened 2020-01-27 15:25 UTC
Does daptin support multilingual fields?

**Comment by artpar** [comment] 2020-01-28 02:53
What do you mean by multilingual fields, can you give an example and usage?

**Comment by panakour** [comment] 2020-01-28 08:17
One usage could be a portfolio project that have services. This services needed to be for example in 3 languages. So every column of the services table should be able to filled in each language.

There is already some headless cms in which support multilingual. example dotcms also you can find a demo here: https://dotcms.com/demo/online-demo
directus cms

**Comment by artpar** [comment] 2020-01-28 10:21
I see. So directus is implementing it was new helper tables for each table you turn translation on. 

This is the save way I am achieving auditing so I can probably add translations to daptin.

Will have to think about the appropriate changes in API for working out with translated fields.

How do you specify language at api level ? Header values or query parameter.

This looks like a good small feature to implement. Thanks for bringing it up.

**Comment by panakour** [comment] 2020-01-28 10:33
> How do you specify language at api level ? Header values or query parameter.

@artpar I think the header is more correct https://stackoverflow.com/questions/7892502/restful-url-where-should-i-put-locale-example-com-en-page-vs-example-com-page

Thank you very much for this. Is the only feature I want to use it in my projects!!!!

**Comment by artpar** [comment] 2020-01-28 10:52
Oh, let me add this for you. If you are wondering about eta, then it would probably be about a week (best case).

**Comment by panakour** [comment] 2020-01-28 11:06
> Oh, let me add this for you. If you are wondering about eta, then it would probably be about a week (best case).

This is perfect!!!! Thank you very much

**Comment by mpartipilo** [comment] 2020-01-31 00:31
I came here to write this issue. I like how Cockpit handles multi-language fields in the UI, and it also handles it via api. I had not tried daptin because of this but now I’m looking forward to it!

**Comment by artpar** [comment] 2020-02-10 17:02
I just merged the multilingual table implementation branch.

Would love to catch issues and unexpected behaviors early on.

You can read about expected behavior here: https://github.com/daptin/daptin/pull/71#issue-370048311

To do: Documentation of this feature and probably one guide would be helpful for everyone.

**Closed** 2020-02-17 06:53 UTC
Labels: need more research, todo :spiral_notepad:
